/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projekpbo;

import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class gudang extends javax.swing.JFrame {
    private DefaultTableModel model;
    Connection con;
    Statement stat;
    ResultSet rs,rs2;
    String sql,user,name;
    /**
     * Creates new form gudang
     */
    public gudang(String username, String nama) {
        initComponents();
        user=username;
        name=nama;
        koneksi DB = new koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
        model=new DefaultTableModel();
        jTable1.setModel(model);
        model.addColumn("Id");
        model.addColumn("Nama");
        model.addColumn("Harga Jual");
        model.addColumn("Harga Pokok");
        model.addColumn("Stok");
        jLabel8.setText(name);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        databarang();
    }
    void databarang()
    {
        //hapus semua data di tabel
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            sql = "SELECT * FROM tb_barang";
            rs = stat.executeQuery(sql);
            int i=0;
            while(rs.next())
            {
                //tampilin semua data barang di tabel
                Object[] o=new Object[5];
                o[0]=rs.getString("id_barang");
                o[1]=rs.getString("nama_barang");
                o[2]=rs.getString("harga_jual");
                o[3]=rs.getString("harga_pokok");
                o[4]=rs.getString("stok");
                model.addRow(o);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
    }
    public gudang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 230, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 117, 230, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 146, 230, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 175, 230, -1));

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 160, 86, 33));

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 120, 86, 35));

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 80, 86, 35));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 490, 160));

        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 24, -1, -1));

        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 40, 20));

        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 120, 27));

        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 174, 120, 28));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gudang.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 390));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        String namabrg=jTextField1.getText();
        String hrg_jual=jTextField3.getText();
        String hrg_pokok=jTextField2.getText();
        String stok=jTextField4.getText();
        //di gudang ini pake 2 gambar, 1 untuk yg simpan, 1 lagi untuk yg edit dan hapus
        //disini ambil dulu nama file gambar yang dipake untuk backgroundnya
        String icon=jLabel1.getIcon().toString();
        File file=new File(icon);
        try {
            //jika gambarnya gudang.jpg (gambar untuk yang simpan/tambah data)
            if(file.getName().equals("gudang.jpg")){
                //insert data barang
                stat.executeUpdate("Insert into tb_barang values "
                        + "(NULL,'"+namabrg+"','"+hrg_jual+"','"+hrg_pokok+"','"+stok+"')");
                databarang();//tampilin ulang data barangnya
                JOptionPane.showMessageDialog(this,"Data berhasil Ditambahkan");
            }else{//else (gambar untuk edit dan hapus)
                int i=jTable1.getSelectedRow();//ambil indeks baris yang dipilih user
                //ambil id barang yang ada di tabel di baris ke i dan kolom 0
                String id=(String) model.getValueAt(i, 0);
                //update data barang
                stat.executeUpdate("update tb_barang set nama_barang='"+namabrg+"',"
                        + "harga_jual='"+hrg_jual+"',harga_pokok='"+hrg_pokok+"',"
                        + "stok='"+stok+"' where id_barang='"+id+"'");
                //tampilin lagi
                databarang();
                JOptionPane.showMessageDialog(this,"Data berhasil diedit");
                ImageIcon bg=new ImageIcon(getClass().getResource("../img/gudang.jpg"));
                //ubah lagi backgroundnya ke gudang.jpg (untuk tambah data)
                jLabel1.setIcon(bg);
                jLabel3.setVisible(false);
                jLabel4.setVisible(false);
            }
            jTextField1.setText(null);
            jTextField2.setText(null);
            jTextField3.setText(null);
            jTextField4.setText(null);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        //ketika user klik data di tabel, ganti background ke gudang2.jpg (edit,hapus)
        ImageIcon bg=new ImageIcon(getClass().getResource("../img/gudang2.jpg"));
        jLabel1.setIcon(bg);
        jLabel3.setVisible(true);
        jLabel4.setVisible(true);
        int i=jTable1.getSelectedRow();
        //tampilin data barang ke textfield
        jTextField1.setText((String) model.getValueAt(i, 1));
        jTextField3.setText((String) model.getValueAt(i, 2));
        jTextField2.setText((String) model.getValueAt(i, 3));
        jTextField4.setText((String) model.getValueAt(i, 4));
    }//GEN-LAST:event_jTable1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        try {
            int pilihan = JOptionPane.showConfirmDialog(this,"Apakah anda yakin "
                    + "ingin menghapus data?","Hapus",JOptionPane.YES_NO_OPTION);
            if(pilihan==JOptionPane.YES_OPTION){
                int i=jTable1.getSelectedRow();//ambil indeks baris yang dipilih
                String id=(String) model.getValueAt(i, 0);//ambil data id di baris ke i dan kolom 0
                //query hapus data
                stat.executeUpdate("delete from tb_barang where id_barang='"+id+"'");
                JOptionPane.showMessageDialog(this,"Data berhasil dihapus");
                databarang();
                //ubah lagi backgroundnya ke gudang.jpg (untuk tambah data)
                ImageIcon bg=new ImageIcon(getClass().getResource("../img/gudang.jpg"));
                jLabel1.setIcon(bg);
                jLabel3.setVisible(false);
                jLabel4.setVisible(false);
                jTextField1.setText(null);
                jTextField2.setText(null);
                jTextField3.setText(null);
                jTextField4.setText(null);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        //tombol batal
        //ubah backgroundnya ke gudang.jpg (untuk tambah data)
        ImageIcon bg=new ImageIcon(getClass().getResource("../img/gudang.jpg"));
        jLabel1.setIcon(bg);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jTextField1.setText(null);
        jTextField2.setText(null);
        jTextField3.setText(null);
        jTextField4.setText(null);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        new pengeluarangudang(user,name).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gudang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
